version: '3'

services:
  servidor:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "10000:10000"  # Mapeia a porta do host para o contêiner
    networks:
      - rede_passagens

networks:
  rede_passagens:
    driver: bridge
